FROM python:3.10-bullseye AS builder

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV NVIDIA_DISABLE_REQUIRE=1

RUN mkdir /app
WORKDIR /app
COPY ./requirements.txt /app

RUN apt update && \
    apt install --no-install-recommends -y build-essential gcc

RUN pip install --user --no-cache-dir --upgrade --ignore-installed setuptools wheel
RUN pip install --user --no-cache-dir --ignore-installed faiss-gpu fairseq gradio ffmpeg ffmpeg-python praat-parselmouth pyworld numpy==1.23.5 numba==0.56.4 librosa==0.9.1
RUN pip install --user --no-cache-dir --ignore-installed --no-deps -r requirements.txt \
&& pip install --user --no-cache-dir -v "torch==2.0.0" \
&& pip install --user --upgrade pip \
&& pip install --user --upgrade --no-cache-dir lxml \
&& pip install --user --no-cache-dir --upgrade ffmpy

FROM nvidia/cuda:12.6.0-cudnn-runtime-ubuntu24.04

RUN apt-get update && apt-get --no-install-recommends -y install build-essential  software-properties-common \
&& add-apt-repository -y ppa:deadsnakes/ppa \
&& apt-get install --no-install-recommends -y python3.10 python3-distutils && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 && \
&& apt install --no-install-recommends -y python3-pip python3-setuptools python3-dev ffmpeg \
&& rm -rf /var/cache/apt  && apt clean && rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV NVIDIA_DISABLE_REQUIRE=1

WORKDIR /app
COPY --from=builder /root/.local/lib/python3.10/site-packages /usr/local/lib/python3.10/dist-packages
COPY . /app