FROM nvidia/cuda:12.6.0-cudnn-runtime-ubuntu24.04

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

WORKDIR /app
COPY ./requirements.txt /app

RUN apt-get -y install build-essential python3-dev ffmpeg
RUN pip install --upgrade setuptools wheel
RUN pip install --upgrade pip
RUN pip install faiss-gpu fairseq gradio ffmpeg ffmpeg-python praat-parselmouth pyworld numpy==1.23.5 numba==0.56.4 librosa==0.9.1
RUN pip install -r requirements.txt
RUN pip install --upgrade lxml
RUN pip install --upgrade ffmpy
RUN apt-get update
RUN apt -y install -qq aria2

RUN python3 -m pip install nvidia-cuda-runtime-cu12

COPY . /app


