FROM python:3.10-bullseye AS builder

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN mkdir /app
WORKDIR /app
COPY ./requirements.txt /app

RUN apt-get update
RUN apt-get -y install build-essential python3-dev
RUN apt install --no-install-recommends -y build-essential gcc

RUN pip install --no-cache-dir --upgrade --ignore-installed --target=/app/reqs setuptools wheel
RUN pip install --no-cache-dir --ignore-installed --target=/app/reqs faiss-gpu fairseq gradio ffmpeg ffmpeg-python praat-parselmouth pyworld numpy==1.23.5 numba==0.56.4 librosa==0.9.1
RUN pip install --no-cache-dir --ignore-installed --no-deps --target=/app/reqs -r requirements.txt \
&& pip install --no-cache-dir --target=/app/reqs -v "torch==2.0.0" \
&& pip install --upgrade pip \
&& pip install --upgrade --no-cache-dir --target=/app/reqs lxml \
&& pip install --no-cache-dir --upgrade --target=/app/reqs ffmpy

FROM nvidia/cuda:12.6.0-cudnn-runtime-ubuntu24.04

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

RUN apt-get update && apt-get --no-install-recommends -y install build-essential  software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get install --no-install-recommends -y python3.10
RUN apt install --no-install-recommends -y python3-pip python3-setuptools python3.10-dev ffmpeg
RUN rm -rf /var/cache/apt  && apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/reqs /app/reqs
ENV PYTHONPATH=/app/reqs:$PYTHONPATH
COPY --from=builder /root/.local/lib/python3.10/site-packages /root/.local/lib/python3.10/site-packages
#COPY --from=builder /root/.local /root/.local

#ENV PATH=/root/.local/bin:$PATH

COPY . /app