#syntax=docker/dockerfile:1.7-labs
FROM python:3.10-bullseye AS builder

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

RUN mkdir /app
WORKDIR /app
COPY ./requirements.txt /app

RUN apt-get update
RUN apt-get -y install build-essential python3-dev
RUN apt install --no-install-recommends -y build-essential gcc

RUN pip install --no-cache-dir --upgrade --ignore-installed --target=/app/reqs setuptools wheel
RUN pip install --no-cache-dir --ignore-installed --target=/app/reqs torch==2.4.1 faiss-gpu fairseq==0.12.2 gradio==3.34.0 ffmpeg ffmpeg-python==0.2.0 praat-parselmouth==0.4.2 pyworld==0.3.2 numpy==1.23.5 numba==0.56.4 librosa==0.9.1
RUN pip install --no-cache-dir --ignore-installed --no-deps --target=/app/reqs -r requirements.txt \
&& pip install --upgrade pip \
&& pip install --upgrade --no-cache-dir --target=/app/reqs lxml \
&& pip install --no-cache-dir --upgrade --target=/app/reqs ffmpy

FROM nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV NVIDIA_DISABLE_REQUIRE=1

RUN apt-get update && apt-get --no-install-recommends -y install build-essential  software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get install --no-install-recommends -y python3.10
RUN apt install --no-install-recommends -y python3-pip python3-setuptools python3.10-dev ffmpeg
RUN rm -rf /var/cache/apt  && apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/reqs /app/reqs
ENV PYTHONPATH=/app/reqs:$PYTHONPATH

RUN cd reqs && rm -r -f pathlib*
RUN cd ..

COPY --exclude=main.py --exclude=launch_rvc.py . /app
COPY launch_rvc.py /app
COPY main.py /app
