# Generated by Django 4.2.8 on 2024-08-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voice",
            name="image",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Обложка голоса (можно с любым расширением)",
            ),
        ),
    ]
