# Generated by Django 4.2.8 on 2024-08-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="subscription",
        ),
        migrations.AddField(
            model_name="subscription",
            name="voice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="bot.voice",
            ),
        ),
    ]
