# Generated by Django 4.2.8 on 2024-02-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="slug"),
        ),
    ]
