# Generated by Django 4.2.8 on 2024-08-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_remove_category_subscription_subscription_voice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="voice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="bot.voice",
            ),
        ),
    ]
