# Generated by Django 4.2.8 on 2024-08-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_alter_subscription_voice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="voice",
        ),
        migrations.AddField(
            model_name="voice",
            name="subscriptions",
            field=models.ManyToManyField(to="bot.subscription"),
        ),
    ]
