services:
  preclient:
    build: ./preclient
    image: managernode:5000/preclient:latest
    pull_policy: build
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile_GPU

    image: managernode:5000/client:latest
    pull_policy: build

  django:
    build: ./django_bot
    image: managernode:5000/django:latest
    pull_policy: build

  payment-api:
    build: ./payment-service
    image: managernode:5000/payment-api:latest
    pull_policy: build
