version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
      - "15672:15672"
      - "5672:5672"

  bot:
    build: ./django_bot
    container_name: bot
    command: ["python", "start_bot.py"]
    depends_on:
      - rabbitmq
      - postgres
    restart:
      always
    env_file:
      - .env
    volumes:
      - $HOME/media-data/${USER_VOICES_PROCESSED_VOLUME}:${USER_VOICES_PROCESSED_VOLUME}
      - $HOME/media-data/${USER_VOICES_RAW_VOLUME}:${USER_VOICES_RAW_VOLUME}

  django:
    build: ./django_bot
    container_name: django
    command: sh -c 'python manage.py makemigrations bot && 
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:3000'
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - bot
    restart:
      always
    env_file:
      - .env
    volumes:
      - $HOME/media-data:/app/media/covers/
      - $HOME/media-data/${VOICES_VOLUME}:${VOICES_VOLUME}

  redis:
    container_name: redis
    image: redis
    command: ["redis-server"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - $HOME/redis/data:/root/redis
    depends_on:
      - bot
    restart:
      always

  preclient:
    container_name: preclient
    build: ./preclient
    command: ["python", "main.py"]
    env_file:
      - .env
    restart:
      always
    depends_on:
      - redis
      - rabbitmq

    # todo: add volume for voices

  client:
    container_name: client
    build: ./client
    command: ["python", "main.py"]
    env_file:
      - .env
#    restart:
#      always
    depends_on:
      - preclient
      - redis
    volumes:
      - $HOME/media-data/${VOICES_VOLUME}:${VOICES_VOLUME}
      - $HOME/media-data/${USER_VOICES_PROCESSED_VOLUME}:${USER_VOICES_PROCESSED_VOLUME}
      - $HOME/media-data/${USER_VOICES_RAW_VOLUME}:${USER_VOICES_RAW_VOLUME}

volumes:
  media-data:

