services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    restart: always
    volumes:  # todo change path for example to another user
      - $HOME/postgresql/data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:15672"]
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s

  redis:
    container_name: redis
    image: redis
    command: ["redis-server"]
    ports:
      - "6379:6379"
    volumes:  # todo change path for example to another user
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - $HOME/redis/data:/root/redis
    # depends_on:
    #   - bot
    restart:
      always

  preclient:
    container_name: preclient
    build: ./preclient
    command: ["python", "main.py"]
    env_file:
      - .env
    restart:
      always
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  client:
    container_name: client
    build: ./client
    command: ["python", "main.py"]
    env_file:
      - .env
    restart:
      always
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - type: volume
        source: models-volume
        target: /app/weights
      - type: volume
        source: raw-voices-volume
        target: ${USER_VOICES_RAW_VOLUME}
      - type: volume
        source: processed-voices-volume
        target: ${USER_VOICES_PROCESSED_VOLUME}

  bot:
    build: ./django_bot
    container_name: bot
    command: ["python", "start_bot.py"]
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    restart:
      always
    env_file:
      - .env
    volumes:
      - type: volume
        source: raw-voices-volume
        target: ${USER_VOICES_RAW_VOLUME}
      - type: volume
        source: processed-voices-volume
        target: ${USER_VOICES_PROCESSED_VOLUME}
      - type: volume
        source: covers-volume
        target: /app/media/covers
      - type: volume
        source: dem-volume
        target: ${DEM_VOLUME}


  django:
    build: ./django_bot
    container_name: django
#    command: gunicorn config.asgi:application -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000

    command: sh -c 'python manage.py makemigrations && 
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:3000'
    ports:
      - "3000:3000"
#    ports:
#      - "8000:80"
    depends_on:
      postgres:
        condition: service_started
    restart:
      always
    env_file:
      - .env
    volumes:
      - type: volume
        source: models-volume
        target: ${MODELS_VOLUME}
      - type: volume
        source: dem-volume
        target: ${DEM_VOLUME}
      - type: volume
        source: covers-volume
        target: /app/media/covers


#  contentDistributer-nginx:
#    container_name: nginx
#    image: nginx:latest
#    ports:
#      - "80:80"
#    env_file:
#      - .env
#    volumes:
#      - ~/covers-volume:/data/covers:rw
##      - ./my_nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
#    restart:
#      always


volumes:
  # todo create models-data-volume / subscriptions-data-volume instead models, cover, dem
  models-volume:
  covers-volume:
  dem-volume:
  processed-voices-volume:
  raw-voices-volume:

