services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    # restart: always
    volumes:
      - /home/postgres/db_data:/var/lib/postgresql/data
      - /home/postgres/backups:/backups
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 5s
      # update_config:
      #   parallelism: 1
      #   delay: 10s
      #   order: start-first
      #   monitor: 10s
      #   failure_action: pause
      # rollback_config:
      #   parallelism: 1
      #   delay: 20s
      #   failure_action: pause
      #   monitor: 0s 
      #   max_failure_ratio: 0
      #   order: start-first

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: rabbitmq
    # restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        monitor: 10s
        failure_action: pause
      rollback_config:
        parallelism: 1
        delay: 20s
        failure_action: pause
        monitor: 0s 
        max_failure_ratio: 0
        order: start-first

  redis:
    container_name: redis
    image: redis
    command: ["redis-server"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart:
      always
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        monitor: 10s
        failure_action: pause
      rollback_config:
        parallelism: 1
        delay: 20s
        failure_action: pause
        monitor: 0s 
        max_failure_ratio: 0
        order: start-first

  preclient:
    container_name: preclient
    image: localhost:5000/preclient:latest
    # build: ./preclient
    command: ["python", "main.py"]
    env_file:
      - .env
    restart:
      always
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        monitor: 10s
        failure_action: pause
      rollback_config:
        parallelism: 1
        delay: 20s
        failure_action: pause
        monitor: 0s 
        max_failure_ratio: 0
        order: start-first

  client:
    container_name: client
    image: localhost:5000/client:latest
    # build: ./client
    command: ["python", "main.py"]
    env_file:
      - .env
    # restart:
    #   always
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy
    #   redis:
    #     condition: service_started
    volumes:
      - type: volume
        source: media-data-volume
        target: /app/weights
      - type: volume
        source: voices-volume
        target: ${USER_VOICES}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        monitor: 10s
        failure_action: pause
      rollback_config:
        parallelism: 1
        delay: 20s
        failure_action: pause
        monitor: 0s 
        max_failure_ratio: 0
        order: start-first


  bot:
    # build: ./django_bot
    image: localhost:5000/bot:latest
    container_name: bot
    command: ["python", "start_bot.py"]
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy
    #   db:
    #     condition: service_started
    # restart:
    #   always
    env_file:
      - .env
    volumes:
      - type: volume
        source: voices-volume
        target: ${USER_VOICES}
      - type: volume
        source: media-data-volume
        target: ${MEDIA_DATA_VOLUME}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        monitor: 10s
        failure_action: pause
      rollback_config:
        parallelism: 1
        delay: 20s
        failure_action: pause
        monitor: 0s 
        max_failure_ratio: 0
        order: start-first


  django:
    # build: ./django_bot
    image: localhost:5000/django:latest
    container_name: django
    command: sh -c 'python manage.py migrate --noinput && 
                    python manage.py collectstatic --noinput --clear &&
                    gunicorn config.asgi:application -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000'
    expose:
      - 8000
    # depends_on:
    #   db:
    #     condition: service_started
    # restart:
    #   always
    env_file:
      - .env
    volumes:
      - type: volume
        source: media-data-volume
        target: ${MEDIA_DATA_VOLUME}
      - type: volume
        source: static_volume
        target: /app/static
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        monitor: 10s
        failure_action: pause
      rollback_config:
        parallelism: 1
        delay: 20s
        failure_action: pause
        monitor: 0s 
        max_failure_ratio: 0
        order: start-first

  proxy-server:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - type: volume
        source: static_volume
        target: /app/static
    # restart:
    #   always
    # depends_on:
    #   - django
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        monitor: 10s
        failure_action: pause
      rollback_config:
        parallelism: 1
        delay: 20s
        failure_action: pause
        monitor: 0s 
        max_failure_ratio: 0
        order: start-first


volumes:
  static_volume:
  media-data-volume:
  voices-volume:

