services:
  preclient:
    build: ./preclient
    image: localhost:5000/preclient:latest
    pull_policy: build
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: localhost:5000/client:latest
    pull_policy: build

  bot:
    build: ./django_bot
    image: localhost:5000/bot:latest
    pull_policy: build

  django:
    build: ./django_bot
    image: localhost:5000/django:latest
    pull_policy: build

  payment-api:
    build: ./payment-service
    image: localhost:5000/payment-api
    pull_policy: build
