services:
  preclient:
    build: ./preclient
    image: localhost:5000/preclient:latest
    pull_policy: build
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile_GPU

    image: localhost:5000/client:latest
    pull_policy: build

  djangobot:
    build: ./django_bot
    image: localhost:5000/djangobot:latest
    pull_policy: build

  payment-api:
    build: ./payment-service
    image: localhost:5000/payment-api
    pull_policy: build
