image: ubuntu:latest # why not aplpine?

stages:
  - build

job 1:
  stage: build
  tags:
    - docker
  when: manual
  scripts:
    - cd arbuzik-rvc-bot
    - apt-get update -y
    - apt-get install openssh-client -y
    - echo $SSH_KEY > id_ed25519
    - chmod 600 id_ed25519
#    - ssh -o "StrictHostKeyChecking=no" -p $SSH_PORT -i id_ed25519 $SERVER_USER@$SERVER_IP "docker compose down && git pull origin main && docker compose build && docker compose up -d"