# Generated by Django 4.2.8 on 2024-04-02 12:36

from django.db import migrations
from parser.main import parser


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial.py")
    ]

    operations = [
        migrations.RunPython(parser)
    ]
