# Generated by Django 4.2.8 on 2023-12-19 16:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_index",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="index of category"
                    ),
                ),
                (
                    "category_name",
                    models.CharField(max_length=200, verbose_name="category name"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="CharacterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_index",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="index of model"
                    ),
                ),
                ("file_path", models.TextField(verbose_name="path of file")),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="sub name")),
                (
                    "time_voice_limit",
                    models.IntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="limit of voice's time",
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        default=1.0,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                        verbose_name="price of sub",
                    ),
                ),
                (
                    "days_limit",
                    models.IntegerField(
                        default=1, null=True, verbose_name="limit of days"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database_app.category",
                    ),
                ),
                (
                    "character_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database_app.charactermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        editable=False,
                        max_length=250,
                        unique=True,
                        verbose_name="telegram id",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=250,
                        verbose_name="user name",
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(max_length=200, verbose_name="Sub status"),
                ),
                (
                    "subscription_final_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="subscription final date",
                    ),
                ),
                (
                    "subscription_usage_limit",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="days limit",
                    ),
                ),
                (
                    "tune",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="tune"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database_app.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
