# Generated by Django 4.2.8 on 2025-03-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_nickname",
            field=models.CharField(
                blank=True,
                default="unknown",
                max_length=100,
                null=True,
                verbose_name="telegram nick name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                default="unknown",
                max_length=100,
                null=True,
                verbose_name="telegram username",
            ),
        ),
    ]
