name: ArbuzikAI deploy
on:
  push:
    branches:
      - main
      - dev
jobs:

  deploy:
    name: deployment
    runs-on: ubuntu-latest
    steps:
    - name: Deploy main branch
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_PROD }}
        username: ${{ secrets.SSH_USER_PROD }}
        key: ${{ secrets.SSH_KEY_PROD }}
        port: ${{ secrets.SSH_PORT_PROD }}
        script: |
          cd arbuzikAIService/
          git switch main
          git pull origin main
          docker compose -f docker-compose.build.yml build
          docker push localhost:5000/preclient:latest
          docker push localhost:5000/client:latest
          docker push localhost:5000/django:latest
          docker push localhost:5000/payment-api:latest
          docker stack rm arb
          docker stack deploy -c docker-compose.deploy.yml arb
          docker builder prune -af
#          docker service update --image localhost:5000/payment-api:latest arb_payment-api
#          docker service update --image localhost:5000/payment-api:latest arb_payment-listener
#          docker service update --image localhost:5000/django:latest arb_bot
#          docker service update --image localhost:5000/django:latest arb_django
#          docker service update --image localhost:5000/django:latest arb_celery-worker
#          docker service update --image localhost:5000/django:latest arb_celery-scheduler
#          docker service update --image localhost:5000/client:latest arb_client
#          docker service update --image localhost:5000/preclient:latest arb_preclient
#          docker service update --image localhost:5000/preclient:latest arb_prometheus-server

#    - name: Deploy dev branch
#      if: github.ref == 'refs/heads/dev'
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.SSH_HOST_PROD }}
#        username: ${{ secrets.SSH_USER_PROD }}
#        key: ${{ secrets.SSH_KEY_PROD }}
#        port: ${{ secrets.SSH_PORT_PROD }}
#        script: |
#          cd arbuzikAIService/
#          git checkout dev
#          git pull origin dev
##          docker compose down
##          docker compose build
##          docker compose up -d
##          docker system prune --force
##          docker system prune --volumes --force
#
