name: ArbuzikAI deploy
on:
  push:
    branches:
      - main
jobs:

  deploy:
    name: deployment
    runs-on: ubuntu-latest
    steps:
    - name: build project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_PROD }}
        username: ${{ secrets.SSH_USER_PROD }}
        key: ${{ secrets.SSH_KEY_PROD }}
        script: |
          cd arbuzik-rvc-bot/
          docker compose down
          git pull origin main
          docker compose build
          docker compose up -d
